### PR TITLE
fix: add parameters types to mutate on useMutationFlow

### LINKED ISSUE #572: FIx useMutationFlow types
The returned mutate function is defined as with no argument, then sometimes you need to pass an argument for example:

```
const useRejectRideOffer = () => {
    const { fetchAsync, isLoading } = useAuthFetch({
        baseUrl: BASE_URL,
    });
    const { mutate } = useMutationFlow({
        mutation: async (rideId: string): Promise<Result> => {
            const result = await fetchAsync<Result>(`/ride-requests/${rideId}/reject`, {
                method: 'PUT',
            });
            return result;
        },
        successMessage: 'Ride rejected sucessfully.',
        errorMessage: 'There was an error.Please try again.',
    });

    return useMemo(() => ({
        rejectRide: async (rideId: string) => {
            const result = await confirmModal({
                variant: 'destructive',
                header: 'Reject Ride',
                question: "This ride will be rejected. You can't undo this action.",
                okButtonLabel: 'Reject',
            });
            if (result) {
                // here we get a type error because the mutate func returned by useMutationFlow does not expect any argument
                await mutate(rideId);
            }
        },
        isLoading,
    }), [isLoading, mutate]);
};
```

### PR DESCRIPTION
**Pull request by HellWolf93**
fix #572

### CODE REVIEW

File: packages/hooks/src/useMutationFlow/index.d.ts [hunk 1]
```diff
@@ -17,4 +17,4 @@ export interface MutationOptions {
     type?: feedbackType | Type;
 }
 
-export default function (opts: MutationOptions): { mutate: () => void };
+export default function (opts: MutationOptions): { mutate: (...args: any[]) => void };
```
Comment (LeandroTorresSicilia) [inline packages/hooks/src/useMutationFlow/index.d.ts:20]: instead of any we should use unknown

**Review by LeandroTorresSicilia — APPROVED** [review]
